from mtg_deck_editor.config import APP_CONFIG
import mtg_deck_editor
import sqlite3

if __name__ == "__main__":
    app = mtg_deck_editor.create_app()
    with app.app_context() as context:
        mtg_deck_editor.db.drop_all()
        mtg_deck_editor.db.create_all()

    import os
    basedir = os.path.abspath(os.path.dirname(mtg_deck_editor.__file__))
    db_uri = os.path.join(basedir, "sqlite\\decks.sqlite")
    imported_sets_uri =  os.path.join(basedir, "sqlite\\AllPrintings.sqlite")
    with sqlite3.connect(db_uri) as connection:
        cursor = connection.cursor()
        cursor.execute("ATTACH DATABASE ? AS mm", [imported_sets_uri])
        cursor.execute("insert into main.sets (code, name) select mm.sets.code, mm.sets.name from mm.sets")
        cursor.execute("""insert into main.setcards (uuid,
                                                    name,
                                                    asciiName,
                                                    setCode,
                                                    artist,
                                                    borderColor,
                                                    defense,
                                                    duelDeck,
                                                    edhrecRank,
                                                    edhrecSaltiness,
                                                    faceFlavorName,
                                                    faceManaValue,
                                                    faceName,
                                                    flavorName,
                                                    flavorText,
                                                    frameVersion,
                                                    hand,
                                                    hasAlternativeDeckLimit,
                                                    hasContentWarning,
                                                    hasFoil,
                                                    hasNonFoil,
                                                    isAlternative,
                                                    isFullArt,
                                                    isFunny,
                                                    isOnlineOnly,
                                                    isOversized,
                                                    isPromo,
                                                    isRebalanced,
                                                    isReprint,
                                                    isReserved,
                                                    isStarter,
                                                    isStorySpotlight,
                                                    isTextless,
                                                    isTimeshifted,
                                                    language,
                                                    layout,
                                                    life,
                                                    loyalty,
                                                    manaCost,
                                                    manaValue,
                                                    number,
                                                    originalReleaseDate,
                                                    originalText,
                                                    originalType,
                                                    power,
                                                    rarity,
                                                    securityStamp,
                                                    side,
                                                    signature,
                                                    text,
                                                    toughness,
                                                    type,
                                                    watermark)
                       select   mm.cards.uuid,
                                mm.cards.name,
                                mm.cards.asciiName,
                                mm.cards.setCode,
                                mm.cards.artist,
                                mm.cards.borderColor,
                                mm.cards.defense,
                                mm.cards.duelDeck,
                                mm.cards.edhrecRank,
                                mm.cards.edhrecSaltiness,
                                mm.cards.faceFlavorName,
                                mm.cards.faceManaValue,
                                mm.cards.faceName,
                                mm.cards.flavorName,
                                mm.cards.flavorText,
                                mm.cards.frameVersion,
                                mm.cards.hand,
                                mm.cards.hasAlternativeDeckLimit,
                                mm.cards.hasContentWarning,
                                mm.cards.hasFoil,
                                mm.cards.hasNonFoil,
                                mm.cards.isAlternative,
                                mm.cards.isFullArt,
                                mm.cards.isFunny,
                                mm.cards.isOnlineOnly,
                                mm.cards.isOversized,
                                mm.cards.isPromo,
                                mm.cards.isRebalanced,
                                mm.cards.isReprint,
                                mm.cards.isReserved,
                                mm.cards.isStarter,
                                mm.cards.isStorySpotlight,
                                mm.cards.isTextless,
                                mm.cards.isTimeshifted,
                                mm.cards.language,
                                mm.cards.layout,
                                mm.cards.life,
                                mm.cards.loyalty,
                                mm.cards.manaCost,
                                mm.cards.manaValue,
                                mm.cards.number,
                                mm.cards.originalReleaseDate,
                                mm.cards.originalText,
                                mm.cards.originalType,
                                mm.cards.power,
                                mm.cards.rarity,
                                mm.cards.securityStamp,
                                mm.cards.side,
                                mm.cards.signature,
                                mm.cards.text,
                                mm.cards.toughness,
                                mm.cards.type,
                                mm.cards.watermark
                       from     mm.cards""")
        connection.commit()
